import { Cairo, Manrope } from "next/font/google";
import "./globals.css";
import Links from "./components/Links";
import Header from "./components/Header";

import BackToTop from "./components/ScrollTop";
import Footer from "./components/Footer";

import initTranslations from "../i18n";

import TranslationsProvider from "./contexts/TranslationsProvider";

import { dir } from "i18next";

const manrope = Manrope({ subsets: ["latin"], weight: "500" });
const cairo = Cairo({ subsets: ["latin"], weight: "500" });
const i18nNamespces = [
  "default",
  "services",
  "about",
  "links",
  "common",
  "header",
  "swipper",
  "footer",
  "contact",
];

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ params: { locale }, children }) {
  const { resources } = await initTranslations(locale, i18nNamespces);

  const lang = locale == "ar" ? cairo.className : manrope.className;

  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={lang}>
        <TranslationsProvider
          resources={resources}
          locale={locale}
          namespaces={i18nNamespces}
        >
          <Links />
          <Header />
          {children}
          <BackToTop />
          <Footer />
        </TranslationsProvider>
      </body>
    </html>
  );
}
